### ISSUE TITLE
{% trans %} don't work (php7)

### ISSUE THREAD

**Issue by celtic34fr** [Saeven/zf2-circlical-trans#1]
Hello,
I try to install zfctwig including creating errors templates. As I have some trouble to get translation, I install your module, and it works fine.
But, I must use {{ translate('string') }} or {{ translate(var) }} to get the right translation.

I use nginx server, with Php7.0.3 (OS Ubuntu 15.10). When i try to use 'trans' node, or 'trans'/'endtrans' nodes, I only get the original string directly or content in variable. I'm puzzle, and don't understand what happens.

**Comment by Saeven** [comment]
Hey.

I'm using PHP7 as well, no issues.  Few questions:

**You have gettext installed?**
The Zend MVCTranslator doesn't use gettext, but twig/trans do.  This could explain cases where one works, but not the other.

**Your translations are in the gettext-format folder?**
 e.g., module\Application\language\en_US\LC_MESSAGES\default.mo

**You aren't defining 'translator' in your service manager anywhere?**
The module defines 'translator' as an alias to MvcTranslator

**You've configured your translator as required? This config isn't being overridden somewhere?**
example:

```
'translator' => array(
        'locale' => 'en_US',
        'translation_file_patterns' => array(
            array(
                'type'          => 'gettext',
                'base_dir'      => __DIR__ . '/../language',
                'pattern'       => '%s/LC_MESSAGES/default.mo',
                'text_domain'   => 'default',
            ),
            array(
                'type'          => 'gettext',
                'base_dir'      => __DIR__ . '/../language',
                'pattern'       => '%s/LC_MESSAGES/errors.mo',
                'text_domain'   => 'errors',
            ),
        ),
    ),
```

**You have a utf-8 locale generated for your language? For example, if I am translating to fr_CA, I need to have the fr_CA.UTF-8 locale installed on the system**
You can check locales with locale -a.   If it isn't there, you issue:
sudo locale-gen fr_CA
sudo locale-gen fr_CA.UTF-8

Let me know if this helps!

**Comment by celtic34fr** [comment]
Hi!,
1rst, gettext is enable (read in php_info() output),
2nd I use the default translations files give by ZF2 in Application/language,
3rd I have an error at first, so i comment the line >'translator' => 'Zend\Mvc\Service\TranslatorServiceFactory',< in Application/config/module.config.php, then i have no errors more,
4th I use the same translator configuration, but my pattern is  '%s.mo'.

i'm try to generate locale for my system (sudo locale-gen fr_FR, ...), but i have the same effect.
During my research, i find than {{ translate() }} call ZF2 viewHelper translate.

If i can help you by sending my project, can you give my an email address to send it in the best condition.

Gilbert ARMENGAUD
(Béziers - Languedoc - France)

**Comment by Saeven** [comment]
Sure man, send it over I can check it out tonight.  saeven at saeven dot net

**Comment by Saeven** [comment]
Got your source, checked it out.  You were just missing a few things.  I tested using fr_CA which I have installed, but it's rinse-and-repeat for your fr_FR:

This was the crux of the issue (above):
**Your translations are in the gettext-format folder?**
e.g., module\Application\language\en_US\LC_MESSAGES\default.mo

First thing I did was to create that gettext spec, moving the default ZF2 Skeleton App fr_CA.mo into module/Application/language/fr_CA/LC_MESSAGES/default.mo

Then I modified your bootstrap to test my language:

```
public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $moduleRouteListener = new ModuleRouteListener();
        $moduleRouteListener->attach($eventManager);

        $application    = $e->getApplication();
        $default_locale = 'fr_CA';
        $other_locales  = [ 'en_US' ];

        if( PHP_SAPI != 'cli' )
        {
            $headers = $application->getRequest()->getHeaders();

            if( $headers->has( 'Accept-Language' ) )
            {
                $locales = $headers->get( 'Accept-Language' )->getPrioritized();
                /** @var LanguageFieldValuePart $locale */
                foreach( $locales as $locale )
                {
                    if( !!($match = Locale::lookup( $other_locales, $locale->getTypeString() )) )
                    {
                        Locale::setDefault( $match );
                        break;
                    }
                }

                if( !$match )
                    Locale::setDefault( $default_locale );
            }
            else
            {
                Locale::setDefault( $default_locale );
            }
        }
        else
        {
            Locale::setDefault( $default_locale );
        }

        setlocale( LC_ALL, Locale::getDefault() );
    }
```

Then -- poof, French.  I'll send you a zip of your codebase back.  I added a small trans block to your main twig up here.

http://i.imgur.com/bpVuv1h.png

**Comment by Saeven** [comment]
Sorry also to have taken awhile, day job takes priority! ;)

**Comment by carlosanjos** [comment]
Hello, I'm having the exact same problem, I tried your solution, but the tags {% trans %} still doesn't work.

```
<h3>{% trans %}Follow Development{% endtrans %}</h3>
<h3>{{ translate('Follow Development') }}</h3>
```

The first line doesn't work, but the seconds translate the text properly.
